Inserisci uno o più host separati da spazi:
marziodemo proxmox01 rocky01

👉 Ultima versione trovata:
 - DEB: https://monitoring.nethlab.it/monitoring/check_mk/agents/check-mk-agent_2.4.0p12-1_all.deb
 - RPM: https://monitoring.nethlab.it/monitoring/check_mk/agents/check-mk-agent-2.4.0p12-1.noarch.rpm

============================
➡️  Installo + configuro marziodemo
============================
👉 Host RHEL/CentOS/Rocky rilevato, installo RPM...
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:check-mk-agent-2.4.0p12-1       ################################# [100%]
👉 Disabilito TLS e socket systemd standard...
👉 Creo unit systemd per agent plain...
👉 Ricarico systemd...
👉 Abilito e avvio il nuovo socket...
✅ Plain agent attivo. Test locale:
<<<check_mk>>>
Version: 2.4.0p12
Hostname: marziodemo
AgentOS: linux
Uptime: 12345

============================
➡️  Installo + configuro proxmox01
============================
👉 Host Debian/Ubuntu rilevato, installo DEB...
Selecting previously unselected package check-mk-agent.
(Reading database ... 123456 files and directories currently installed.)
Preparing to unpack .../check-mk-agent_2.4.0p12-1_all.deb ...
Unpacking check-mk-agent (2.4.0p12-1) ...
Setting up check-mk-agent (2.4.0p12-1) ...
👉 Disabilito TLS e socket systemd standard...
👉 Creo unit systemd per agent plain...
👉 Ricarico systemd...
👉 Abilito e avvio il nuovo socket...
✅ Plain agent attivo. Test locale:
<<<check_mk>>>
Version: 2.4.0p12
Hostname: proxmox01
AgentOS: linux
Uptime: 6789

============================
➡️  Installo + configuro rocky01
============================
👉 Host RHEL/CentOS/Rocky rilevato, installo RPM...
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:check-mk-agent-2.4.0p12-1       ################################# [100%]
👉 Disabilito TLS e socket systemd standard...
👉 Creo unit systemd per agent plain...
👉 Ricarico systemd...
👉 Abilito e avvio il nuovo socket...
✅ Plain agent attivo. Test locale:
<<<check_mk>>>
Version: 2.4.0p12
Hostname: rocky01
AgentOS: linux
Uptime: 4321

