#!/usr/bin/env python3
# mail_realip con grafici abilitati
# HTML Email: yes
# Bulk: yes

import os
from cmk.notification_plugins import mail as _mail

def main():
    # NON disattivare i grafici (rimuovo _no_graphs)
    
    # --- gestione real_ip invariata ---
    real_ip = os.environ.get("NOTIFY_HOSTLABEL_real_ip")
    if real_ip:
        os.environ["HOSTADDRESS"] = real_ip
        os.environ["NOTIFY_HOSTADDRESS"] = real_ip
        os.environ["NOTIFY_MONITORING_HOST"] = real_ip
        if "NOTIFY_HOSTOUTPUT" in os.environ:
            os.environ["NOTIFY_HOSTOUTPUT"] = os.environ["NOTIFY_HOSTOUTPUT"].replace(
                os.environ.get("NOTIFY_HOSTADDRESS", "127.0.0.1"), real_ip
            )
    # ---------------------------

    # Chiama mail standard CheckMK CON grafici abilitati
    _mail.main()

if __name__ == "__main__":
    main()
