Inserisci uno o piÃ¹ host separati da spazi:
marziodemo proxmox01 rocky01

ðŸ‘‰ Ultima versione trovata:
 - DEB: https://monitoring.nethlab.it/monitoring/check_mk/agents/check-mk-agent_2.4.0p12-1_all.deb
 - RPM: https://monitoring.nethlab.it/monitoring/check_mk/agents/check-mk-agent-2.4.0p12-1.noarch.rpm

============================
âž¡ï¸  Installo + configuro marziodemo
============================
ðŸ‘‰ Host RHEL/CentOS/Rocky rilevato, installo RPM...
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:check-mk-agent-2.4.0p12-1       ################################# [100%]
ðŸ‘‰ Disabilito TLS e socket systemd standard...
ðŸ‘‰ Creo unit systemd per agent plain...
ðŸ‘‰ Ricarico systemd...
ðŸ‘‰ Abilito e avvio il nuovo socket...
âœ… Plain agent attivo. Test locale:
<<<check_mk>>>
Version: 2.4.0p12
Hostname: marziodemo
AgentOS: linux
Uptime: 12345

============================
âž¡ï¸  Installo + configuro proxmox01
============================
ðŸ‘‰ Host Debian/Ubuntu rilevato, installo DEB...
Selecting previously unselected package check-mk-agent.
(Reading database ... 123456 files and directories currently installed.)
Preparing to unpack .../check-mk-agent_2.4.0p12-1_all.deb ...
Unpacking check-mk-agent (2.4.0p12-1) ...
Setting up check-mk-agent (2.4.0p12-1) ...
ðŸ‘‰ Disabilito TLS e socket systemd standard...
ðŸ‘‰ Creo unit systemd per agent plain...
ðŸ‘‰ Ricarico systemd...
ðŸ‘‰ Abilito e avvio il nuovo socket...
âœ… Plain agent attivo. Test locale:
<<<check_mk>>>
Version: 2.4.0p12
Hostname: proxmox01
AgentOS: linux
Uptime: 6789

============================
âž¡ï¸  Installo + configuro rocky01
============================
ðŸ‘‰ Host RHEL/CentOS/Rocky rilevato, installo RPM...
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:check-mk-agent-2.4.0p12-1       ################################# [100%]
ðŸ‘‰ Disabilito TLS e socket systemd standard...
ðŸ‘‰ Creo unit systemd per agent plain...
ðŸ‘‰ Ricarico systemd...
ðŸ‘‰ Abilito e avvio il nuovo socket...
âœ… Plain agent attivo. Test locale:
<<<check_mk>>>
Version: 2.4.0p12
Hostname: rocky01
AgentOS: linux
Uptime: 4321

